// Generates supabase/seed.sql from the app's sample data (src/lib/seed.ts),
// so the hosted database starts with the same demo accounts and learners.
// Run: npx tsx scripts/generate-seed-sql.ts > supabase/seed.sql
import { createSeed, DEMO_PASSWORD } from '../src/lib/seed'

const PARENT_UUID = '11111111-1111-4111-8111-111111111111'
const TEACHER_UUID = '22222222-2222-4222-8222-222222222222'

const q = (v: unknown) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`)
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`
const arr = (v: string[]) => `array[${v.map(q).join(', ')}]::text[]`
const appId = (id: string) => (id === 'PAR-DEMO' ? PARENT_UUID : id)

function authUser(id: string, email: string, meta: Record<string, unknown>) {
  return `
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, email_change, email_change_token_new, recovery_token)
values ('00000000-0000-0000-0000-000000000000', ${q(id)}, 'authenticated', 'authenticated', ${q(email)},
  extensions.crypt(${q(DEMO_PASSWORD)}, extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}'::jsonb, ${j(meta)}, now(), now(), '', '', '', '');
insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (gen_random_uuid(), ${q(id)}, ${q(id)}, ${j({ sub: id, email, email_verified: true })}, 'email', now(), now(), now());`
}

async function main() {
  const db = await createSeed(async () => '')
  const parent = db.parents[0]
  const teacher = db.teachers[0]
  const out: string[] = []

  out.push(`-- LEIF demo data. Generated by scripts/generate-seed-sql.ts — do not edit by hand.
-- Run AFTER schema.sql, in the Supabase SQL Editor. Safe to re-run: it resets the demo data.
-- Demo logins (password ${DEMO_PASSWORD}): ${parent.email} · teacher ${teacher.id} at "${teacher.school}" · learner STU-001 / PIN 1234

begin;
delete from public.notifications where user_id in (${q(PARENT_UUID)}, ${q(teacher.id)});
delete from public.students where id in (${db.students.map(s => q(s.id)).join(', ')});
delete from auth.users where id in (${q(PARENT_UUID)}, ${q(TEACHER_UUID)});`)

  // Accounts — the on_auth_user_created trigger creates their profiles.
  out.push(authUser(PARENT_UUID, parent.email, { role: 'parent', first_name: parent.firstName, last_name: parent.lastName }))
  out.push(authUser(TEACHER_UUID, teacher.email, {
    role: 'teacher', first_name: teacher.firstName, last_name: teacher.lastName,
    teacher_code: teacher.id, school: teacher.school, school_id: teacher.schoolId,
    subjects: teacher.subjects, classes: teacher.classes,
  }))
  out.push(`
update public.profiles set phone = ${q(parent.phone)}, prefs = ${j(parent.prefs)}, created_at = ${q(parent.createdAt)}, terms_accepted_at = ${q(parent.createdAt)} where id = ${q(PARENT_UUID)};
update public.profiles set phone = ${q(teacher.phone)}, title = ${q(teacher.title)}, created_at = ${q(teacher.joined)}, terms_accepted_at = ${q(teacher.joined)} where id = ${q(TEACHER_UUID)};`)

  for (const s of db.students) {
    out.push(`
insert into public.students (id, name, class, gender, age, school, scores, history, attendance, weaknesses, strengths,
  teacher_note, last_updated, status, assignments, parent_name, parent_phone, parent_id, privacy, sample_data)
values (${q(s.id)}, ${q(s.name)}, ${q(s.class)}, ${q(s.gender)}, ${s.age ?? 'null'}, ${q(s.school)}, ${j(s.scores)}, ${j(s.history)},
  ${j(s.attendance)}, ${arr(s.weaknesses)}, ${arr(s.strengths)}, ${q(s.teacherNote)}, ${q(s.lastUpdated)}, ${q(s.status)},
  ${j(s.assignments)}, ${q(s.parentName)}, ${q(s.parentPhone)}, ${s.parentId ? q(appId(s.parentId)) : 'null'}, ${j(s.privacy)}, false);
insert into public.learner_pins (student_id, pin) values (${q(s.id)}, ${q(s.learnerPin)});
insert into public.score_uploads (student_id, uploaded_by, source, term, scores, weaknesses, strengths, note, created_at)
values (${q(s.id)}, ${q(TEACHER_UUID)}, 'teacher', ${q(s.scores[0]?.term ?? 'Second Term')}, ${j(Object.fromEntries(s.scores.map(x => [x.subject, x.score])))},
  ${arr(s.weaknesses)}, ${arr(s.strengths)}, ${q(s.teacherNote)}, ${q(s.lastUpdated)});`)
  }

  out.push('\n' + db.announcements.map(a => `insert into public.announcements (id, teacher_id, teacher_code, title, body, class_target, date)
values (${q(a.id)}, ${q(TEACHER_UUID)}, ${q(a.teacherId)}, ${q(a.title)}, ${q(a.body)}, ${q(a.classTarget)}, ${q(a.date)});`).join('\n'))

  // Relative timestamps ("2 hours ago") are rebuilt at seed time from their offset.
  const now = Date.now()
  out.push('\n' + db.notifications.map(n => {
    const hoursAgo = Math.max(0, Math.round((now - new Date(n.date).getTime()) / 3600_000))
    const date = hoursAgo < 72 ? `now() - interval '${hoursAgo} hours'` : q(n.date)
    return `insert into public.notifications (user_id, kind, title, body, link, read, date)
values (${q(appId(n.userId))}, ${q(n.kind)}, ${q(n.title)}, ${q(n.body)}, ${q(n.link)}, ${n.read}, ${date});`
  }).join('\n'))

  out.push('\n' + db.actions.map(a => `insert into public.support_actions (id, student_id, parent_id, subject, title, started_at, baseline_score, status)
values (${q(a.id)}, ${q(a.studentId)}, ${q(PARENT_UUID)}, ${q(a.subject)}, ${q(a.title)}, ${q(a.startedAt)}, ${a.baselineScore}, ${q(a.status)});`).join('\n'))

  out.push('\ncommit;')
  console.log(out.join('\n'))
}

main()
